Support links metadata for rich text fields #217
enonic/lib-guillotine pull request #218
Opened 2022-03-27 21:26 UTC by anatol-sialitski

2022-03-28 08:41 UTC, rymsha requested changes

2022-03-28 08:41 UTC, rymsha commented on build.gradle
> +    implementation 'org.jsoup:jsoup:1.14.3'
no-go for now :(

2022-03-28 08:41 UTC, rymsha commented on src/main/java/com/enonic/lib/guillotine/macro/HtmlLinkProcessor.java
> +@Deprecated
refactor out private classes, don't deprecate them

2022-03-28 08:41 UTC, rymsha commented on src/main/java/com/enonic/lib/guillotine/macro/ContentLinkProcessorManager.java
> +            trimResults().
what is the benefit?

2022-03-28 08:41 UTC, rymsha commented on src/main/java/com/enonic/lib/guillotine/macro/ContentLinkProcessorManager.java
> +        final String query = urlQuery.startsWith( "?" ) ? urlQuery.substring( 1 ) : urlQuery;
why supporting both formats?

2022-03-28 08:41 UTC, rymsha commented on src/main/java/com/enonic/lib/guillotine/macro/ContentLinkProcessorManager.java
> +            split( query.replace( "&amp;", "&" ) );
this can't be right. It means unescaped query string can be passed. And it means some other symbols are left unescaped.

2022-03-29 16:43 UTC, rymsha requested changes

2022-03-29 16:43 UTC, rymsha commented on docs/api.adoc
> +|Represents details of links which were detected in the HtmlArea value, where value the `href` attribute starts from `content://`, `media://` or `image://`
image too?
Actually it is better to rephrase it, so we don't mention uri scheme,  but explain what they represent (content or media)

2022-03-29 16:43 UTC, rymsha commented on docs/api.adoc
> +|Related media content
Say it is null for non-media content

2022-03-29 16:43 UTC, rymsha commented on docs/api.adoc
> +|Related content
Say it is null for media content

2022-03-29 16:43 UTC, rymsha commented on src/test/java/com/enonic/lib/guillotine/macro/HtmlLinkProcessorTest.java
> +            }, link -> {
Where are tests for links?

2022-03-31 14:49 UTC, rymsha requested changes

2022-03-31 14:49 UTC, rymsha commented on docs/api.adoc
> +|Represents details of links which were detected in the HtmlArea value, which are represent `content` or `media`
```suggestion
|Represents details of links which were detected in the HtmlArea value, which represent `content` or `media`
```

2022-03-31 14:49 UTC, rymsha commented on docs/images/v-541.svg
> +<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="54" height="20"><linearGradient id="s" x2="0" y2="100%"><stop offset="0" stop-color="#bbb" stop-opacity=".1"/
It is a feature release

2022-04-01 10:47 UTC, rymsha requested changes

2022-04-01 10:47 UTC, rymsha commented on src/main/resources/lib/guillotine/generic/page-types.js
> +                type: graphQlLib.GraphQLString,
would be nice to have an enum

2022-04-01 11:23 UTC, anatol-sialitski commented on src/main/resources/lib/guillotine/generic/page-types.js
> +                type: graphQlLib.GraphQLString,
done

2022-04-01 11:43 UTC, rymsha approved these changes

2022-04-01 11:52 UTC, merged